### PR TITLE
Add kubectl to requirements

### PR DESCRIPTION
**Pull request by lhoupert**
I had to do this step to be able to run the `kubectl` command, I thought I would flag it.

### CODE REVIEW

**Comment by antongisli** [comment]
Thanks! Please fix the typo and I'll merge it

**Comment by lhoupert** [comment]
Sorry for that. Done!

**Review by antongisli — APPROVED** [review]

**Comment by antongisli** [comment]
thank you for the contribution @lhoupert !

**Comment by lhoupert** [comment]
Thank you for your tutorial!

Le mar. 15 mars 2022 à 14:46, antongisli ***@***.***> a
écrit :

**Pull request merged**
